# -*- coding: utf-8 -*-
POSTS_PER_PAGE = 5
POST_CONTENT_ON_HOMEPAGE = True
ADMIN_USERNAME = 'allyons16'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$SZQaS63B$36bcc7b597c5d81ea00ebbbbeb3a9a4eb40067cb'
ANALYTICS_ID = ''
GITHUB_USERNAME = 'lyonsa'
CONTACT_EMAIL = 'allyons16@gmail.com'
BLOG_TITLE = 'Lions 8 Lyons'
BLOG_TAGLINE = 'It\'s Allen\'s World'
BLOG_URL = '/'
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = 'V7YAQEQLLOTGMQETPH3YVY7R676IG4H7RIF4DVONK34D76MVUQZA===='
DISQUS_SHORTNAME = ''
USE_ADDTOANY = True
USE_SUBTOME = False
