# -*- coding: utf-8 -*-
POSTS_PER_PAGE = 5
POST_CONTENT_ON_HOMEPAGE = True
ADMIN_USERNAME = 'lyonsa'
ADMIN_PASSWORD = 'pbkdf2:sha1:1000$YrFcTFHJ$f4fddcba54910fbfff43b8f6313b45497ed371ab'
ANALYTICS_ID = 'UA-48332263-1'
GITHUB_USERNAME = 'lyonsa'
CONTACT_EMAIL = 'allyons16@gmail.com'
BLOG_TITLE = 'Lions 8 Lyons'
BLOG_TAGLINE = 'It\'s Allen\'s World'
BLOG_URL = '/'
FONT_NAME = 'Source+Sans+Pro'
SECRET_KEY = 'GFMRPSVMKC7IGYX5P23VIBGO6Z4GTHDSG6C4SXYCLFQV7VVBNSRA===='
DISQUS_SHORTNAME = 'lionsblog'
USE_ADDTOANY = True
USE_SUBTOME = True
